package io.idhub.jwt.error;


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.idhub.jwt.serialisers.InstantWithMilliSecondPrecisionSerializer;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.http.HttpStatus;

import java.time.Instant;
import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@JsonInclude(JsonInclude.Include.NON_NULL)
/**
 * The REST error to return as part of the response
 */
public class IDHubRestErrorResponse {
    /**
     * The trace ID for referring to this issue. Customers will use this trace ID to raise support tickets.
     * From this trace ID, we should be able to extract the logs of this error
     */
    private String traceId;

    /**
     * The timestamp when the exception occurred.
     */
    @JsonSerialize(using = InstantWithMilliSecondPrecisionSerializer.class)
    private Instant timestamp;

    /**
     * The error message with more context about the issue
     */
    private String message;

    /**
     * List of all errors generated by a request.
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private List<IDHubError> errors;

    @JsonIgnore
    private HttpStatus httpStatus;
}
