server:
  port: 8482

spring:
  profiles:
    include:
    - console-logging
  r2dbc:
    host: localhost
    port: 8434
    database: idhub-keys-db
    username: local
    password: local


idhub:
  jwt:
    default:
      jws-algorithm: RS256
      encryption-algorithm: RSA-OAEP-256
      encryption-method: A128CBC-HS256
      key-valid-period:  7200000